version: '3.8'

services:
  webserver:
    container_name: webserver-symfony6-on-hands
    build:
      context: .
    ports:
      - '9000:80'
    volumes:
      - ./app:/var/www/html
    networks:
      - default
    depends_on:
      - database

  database:
    container_name: mysql-db-symfony6-on-hands
    image: mysql:latest
    environment:
      MYSQL_DATABASE: local_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - '9906:3306'
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default

  mailer:
    container_name: mailer-symfony6-on-hands
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  persistent:
